### ISSUE TITLE
Remove federation on migration to CoreDNS version 1.7

### ISSUE THREAD

**Issue by rtheis** [coredns/corefile-migration#53]
With the removal of `federation` plugin in [CoreDNS version 1.7](https://coredns.io/2020/06/15/coredns-1.7.0-release/), it would be ideal if corefile migration removed it.

**Comment by rajansandeep** [comment]
> it would be ideal if corefile migration removed it.

Do you mean removing the option if it's detected in the `Corefile` during migration?

**Comment by rtheis** [comment]
@rajansandeep Yes.  If the option is left, CoreDNS will crash.

**Comment by chrisohaver** [comment]
If a cluster is using federation, then upgrading and removing the federation plugin would also break the cluster.  However, a broken federation DNS is better than completely broken DNS.  Both are a bad situation to _automatically_ migrate a deployment into, but any tool using the migration library _should_ be warning the user that the Corefile contains a plugin that is no longer supported before automatically proceeding.

**Comment by chrisohaver** [comment]
Practically speaking, If a cluster is using federation, then the admin would probably want to do one of three things:
1. leave CoreDNS as is, at the version that still supports federation.
2. manually compile a CoreDNS with the federation plugin in it and manually update to it.
3. "unfederate" the cluster.

If an admin consciously decides to proceed with an upgrade to a version of CoreDNS that no longer supports federation, then we can only assume they have decided to "unfederate" their cluster, in which case removing the plugin makes sense.

**Comment by rtheis** [comment]
@chrisohaver I think this can be closed.  From my perspective, this issue is no longer relevant.
