### ISSUE TITLE
Fork/rewrite Caddyfile parsing?

### ISSUE THREAD

**Issue by dlorenc** [coredns/corefile-migration#56]
I saw the conversaion in #48 around copying the caddyfile parsing logic to avoid needing to import caddy.

It looks like newer versions of caddy (v2 and above) don't directly expose the Dispenser types used here. What do you think the best path forward to trimming the dependency tree might be? It seems relatively straightforward to copy over the old logic. 

I have a draft branch here: https://github.com/dlorenc/corefile-migration/pull/new/caddy that has passing tests and should be merge-able.

**Comment by chrisohaver** [comment]
Thanks for raising this. coredns/coredns uses coredns/caddy which is a stripped down fork of caddy v1 that only includes the bits CoreDNS uses. #58 moves the dependency to there, and the most/all of the same extra package dependency baggage we got from caddyserver/caddy drops out as a result.
